/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransportConfig {
  keypair: Buffer
  /**
   * Timeout for the initial handshake when establishing a connection.
   * The actual timeout is the minimum of this and the [`Config::max_idle_timeout`].
   */
  handshakeTimeout: number
  /** Maximum duration of inactivity in ms to accept before timing out the connection. */
  maxIdleTimeout: number
  /**
   * Period of inactivity before sending a keep-alive packet.
   * Must be set lower than the idle_timeout of both
   * peers to be effective.
   *
   * See [`quinn::TransportConfig::keep_alive_interval`] for more
   * info.
   */
  keepAliveInterval: number
  /**
   * Maximum number of incoming bidirectional streams that may be open
   * concurrently by the remote peer.
   */
  maxConcurrentStreamLimit: number
  /** Max unacknowledged data in bytes that may be send on a single stream. */
  maxStreamData: number
  /**
   * Max unacknowledged data in bytes that may be send in total on all streams
   * of a connection.
   */
  maxConnectionData: number
}
export class Transport {
  static new(config: TransportConfig): Transport
  dial(addr: string): Promise<Connection>
  createListener(addr: string): Listener
}
export class Listener { }
export class Connection { }
export class Stream { }
